### ISSUE TITLE
Invalid option to --combined-json: clone-bin

### ISSUE THREAD

**Issue by redza610** [Kudaes/Fingeth#1]
Hello Kudaes.

I have been trying to test your project, however I have gotten in issue with the following errors : 

On Client side: after I run the main.py , then selected 1 for Register, i got : 
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()
  File "main.py", line 20, in main
    r = ctr.register()
  File "/home/pi/Downloads/Fingeth-master/client/controler.py", line 139, in register
    compiled = compile_source(contract_source_code,import_remappings=["-"]) # Compiled source code
  File "/home/pi/.local/lib/python3.7/site-packages/solc/main.py", line 108, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/pi/.local/lib/python3.7/site-packages/solc/wrapper.py", line 169, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: An error occurred during execution
> command: `solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,userdoc -`
> return code: `1`
> stderr:

> stdout:
Invalid option to --combined-json: clone-bin

On the server side, after I ran server_main.py, I got : 

Socket created
Bind failed.
[Errno 98] Address already in use

I used  the ports 30303 where it listenning to Geth service and the IP address of the server node.

can you please help with appreciation 
Thanks 
Reda

**Comment by Kudaes** [comment]
Hi Reda,

I've seen your email and I'll try to help you out, but unfortunately I've made this project several years ago and I've forgotten a lot about it.

The problem on the client side seems like compilation error in the solc library, you should be able to fix it following this thread: https://github.com/ethereum/py-solc/issues/61

On the other hand, the server side problem seems easier to fix. By default, when you run server_main.py It will try to open a TCP socket on the address 127.0.0.1:5555. The "Address already in use" message is self explanatory: either you have another program listening on TCP port 5555 (use netstat to figure it out) or you don't have enough privileges to start a new socket on that port (try running server_main.py with sudo privileges, but I would say that this is not the error root cause). I recommend you to change the value of the variable PORT of the ServerSocket class (server_main.py file) to start the socket in a different TCP port and this error should dissapear.

I hope this helps you out. Let me know if you have any further question that I can help you with.
Best regards,
Kurosh.
